# Generated by Django 2.0.6 on 2018-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0003_auto_20180711_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualresidency',
            name='ResidencyStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualresidency',
            name='TimeOut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittable_inventory',
            name='BorrowStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittable_inventory',
            name='Borrower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittable_inventory',
            name='DateTimeReturned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audittable_inventory',
            name='Lender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
