# Generated by Django 2.0.6 on 2018-07-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0005_audittable_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittable_inventory',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARC.Inventory'),
        ),
    ]
