# Generated by Django 2.0.6 on 2018-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0007_auto_20180715_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Lab',
            field=models.IntegerField(default=0),
        ),
    ]
