# Generated by Django 2.0.6 on 2018-07-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0008_group_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audittable_inventory',
            old_name='Lender',
            new_name='Admin',
        ),
    ]
