# Generated by Django 2.0.6 on 2018-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0012_inventory_qtyborrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualresidency',
            name='DateTime',
            field=models.DateField(),
        ),
    ]
