# Generated by Django 2.0.6 on 2018-07-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0013_auto_20180724_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Degree',
            fields=[
                ('DegreeID', models.AutoField(primary_key=True, serialize=False)),
                ('DegreeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='Lab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Group',
        ),
        migrations.AddField(
            model_name='group',
            name='GroupName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='GroupStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='Members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='lab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_Laboratory'),
        ),
        migrations.AddField(
            model_name='user',
            name='Adviser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Laboratory',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_Laboratory'),
        ),
        migrations.AddField(
            model_name='user',
            name='Type',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_UserType'),
        ),
        migrations.AddField(
            model_name='user',
            name='adviser',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Adviser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Degree',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_Degree'),
        ),
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_Department'),
        ),
    ]
