# Generated by Django 2.0.6 on 2018-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0014_auto_20180725_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittable_inventory',
            name='Admin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
