# Generated by Django 2.0 on 2018-07-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0015_auto_20180725_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Adviser',
        ),
        migrations.AddField(
            model_name='user',
            name='Remarks',
            field=models.CharField(default='', max_length=250),
        ),
    ]
