# Generated by Django 2.0 on 2018-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0018_auto_20180729_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_laboratory',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
