# Generated by Django 2.0 on 2018-08-02 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0020_auto_20180801_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresidencyschedule',
            name='Schedule',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.Ref_Schedule'),
        ),
        migrations.AlterField(
            model_name='studentresidencyschedule',
            name='Student',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.User'),
        ),
    ]
