# Generated by Django 2.0 on 2018-08-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0021_auto_20180802_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualresidency',
            name='Student',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARC.User'),
        ),
    ]
