# Generated by Django 2.0.6 on 2018-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0023_auto_20180802_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
        migrations.AlterField(
            model_name='studentresidencyschedule',
            name='Student',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='NFCUniqueID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
