# Generated by Django 2.0.6 on 2018-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0024_auto_20180803_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ItemUniqueID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
