# Generated by Django 2.0.6 on 2018-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0026_inventory_itemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencytimeslot',
            name='SchedVar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresidencyschedule',
            name='RefSchedVar',
            field=models.IntegerField(default=0),
        ),
    ]
