# Generated by Django 2.0.6 on 2018-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0027_auto_20181009_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresidencyschedule',
            name='StudentSchedVar',
            field=models.IntegerField(default=0),
        ),
    ]
