# Generated by Django 2.1.2 on 2018-11-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0028_studentresidencyschedule_studentschedvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualresidency',
            name='ResidencyType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
