# Generated by Django 2.1.2 on 2018-11-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0029_actualresidency_residencytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualresidency',
            name='Schedule',
            field=models.CharField(default='', max_length=50),
        ),
    ]
