# Generated by Django 2.0.5 on 2018-11-04 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0030_actualresidency_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresidencyschedule',
            name='DateChanged',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentresidencyschedule',
            name='DateReserved',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
